spring:
  application:
    name: QuoraReactiveApp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: quora_db
      auto-index-creation: true

server:
  port: ${PORT}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.kafka: DEBUG
    reactor.netty: DEBUG
